//
// EventRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventRequest: JSONEncodable {
    /** URL for the server to request on successful subscription to specified service */
    public var url: String?
    /** ServiceID to bind event to. */
    public var serviceid: String?
    /** Valid JSON of Key-value parameters to post to url */
    public var postbody: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["serviceid"] = self.serviceid
        nillableDictionary["postbody"] = self.postbody
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
