//
// ServiceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ServiceRequest: JSONEncodable {
    /** Name of service */
    public var name: String?
    /** Richtext description of item */
    public var desc: String?
    /** Upfront cost of service in hundreds */
    public var price: String?
    /** Recurring monthly cost of subscription */
    public var recurpric: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["desc"] = self.desc
        nillableDictionary["price"] = self.price
        nillableDictionary["recurpric"] = self.recurpric
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
