//
// Variation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Variation: JSONEncodable {
    /** Variation name */
    public var name: String?
    /** New price to set if variation is set (in hundreds) */
    public var priceChange: Double?
    /** System ID of variation */
    public var id: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["priceChange"] = self.priceChange
        nillableDictionary["id"] = self.id
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
