//
// Category.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Category: JSONEncodable {
    /** Name of category */
    public var name: String?
    /** ID of category */
    public var id: String?
    /** ID of parent element. Top level categories are set to root. */
    public var parent: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["id"] = self.id
        nillableDictionary["parent"] = self.parent
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
