//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Order: JSONEncodable {
    /** Order ID */
    public var orderId: String?
    /** Customer email */
    public var infoEmail: String?
    /** Customer first name */
    public var infoFirst: String?
    /** Customer last name */
    public var infoLast: String?
    /** Customer phone number */
    public var phone: String?
    /** Customer billing address matches shipping address */
    public var shipset: Bool?
    /** Customer billing address line &#39;1&#39; */
    public var infoAdr1: String?
    /** Customer billing address line &#39;2&#39; */
    public var infoAdr2: String?
    /** Customer billing city */
    public var infoCty: String?
    /** Customer billing zip code */
    public var infoZip: String?
    /** Customer billing state */
    public var state: String?
    /** Customer shipping address line &#39;1&#39; */
    public var infoSadr1: String?
    /** Customer shipping address line &#39;2&#39; */
    public var infoSadr2: String?
    /** Customer shipping city */
    public var infoScty: String?
    /** Customer shipping zip code */
    public var infoSzip: String?
    /** Customer shipping state */
    public var sstate: String?
    /** Tax amount in hundreds. Must divide by &#39;100&#39; for USD value */
    public var taxAmount: Float?
    /** Shipping total in USD */
    public var shippingAmount: Float?
    /** Checkout total in USD */
    public var amountTotal: Float?
    /** Array of items purchased at checkout */
    public var itemIDs: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["order_id"] = self.orderId
        nillableDictionary["info_email"] = self.infoEmail
        nillableDictionary["info_first"] = self.infoFirst
        nillableDictionary["info_last"] = self.infoLast
        nillableDictionary["phone"] = self.phone
        nillableDictionary["shipset"] = self.shipset
        nillableDictionary["info_adr1"] = self.infoAdr1
        nillableDictionary["info_adr2"] = self.infoAdr2
        nillableDictionary["info_cty"] = self.infoCty
        nillableDictionary["info_zip"] = self.infoZip
        nillableDictionary["state"] = self.state
        nillableDictionary["info_sadr1"] = self.infoSadr1
        nillableDictionary["info_sadr2"] = self.infoSadr2
        nillableDictionary["info_scty"] = self.infoScty
        nillableDictionary["info_szip"] = self.infoSzip
        nillableDictionary["sstate"] = self.sstate
        nillableDictionary["tax_amount"] = self.taxAmount
        nillableDictionary["shipping_amount"] = self.shippingAmount
        nillableDictionary["amount_total"] = self.amountTotal
        nillableDictionary["itemIDs"] = self.itemIDs?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
